url: "" # add client's full domain between the quotes here - ensure to include https:// and ensure there is NO forwardslash at the end. eg "https://example.com"

    
# exclude:
#   - component-library/

include:
  - _cloudcannon

plugins:
  - jekyll-bookshop

bookshop_locations:
  - component-library