seo: 
  site_name:
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_username:
  pinterest_username:
  linkedin_username:
  twitter_username: 
  tiktok_username: 
  youtube_username:
design: 
  dark-text_color: 'rgb(60,60,65)'
  medium-text_color: 'rgb(90,90,95)'
  light-text_color: '#f7f5f3'
  featured-text_color: 'red'
  primary_color: '#B1BAB5'
  secondary_color: '#5F9595'
  dark_color: 'rgb(60,60,65)'
  medium_color: '#ede8e4'
  light_color: '#f7f5f3'
  v-light_color: '#f9f9f9'
  featured_color: '#6495ed'
  accent_color: 'rgb(167, 74, 74)'
  primary_logo_path:
  secondary_logo_path:
  submark_logo_path:
